# Generated by Django 6.0.3 on 2026-03-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EarthquakeReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=64)),
                ('earthquakeX', models.FloatField()),
                ('earthquakeY', models.FloatField()),
                ('rssi', models.IntegerField(blank=True, null=True)),
                ('source_ts', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['node_id', 'created_at'], name='api_earthqu_node_id_d0ce82_idx')],
            },
        ),
        migrations.CreateModel(
            name='ElectricalReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=64)),
                ('amps', models.FloatField()),
                ('rssi', models.IntegerField(blank=True, null=True)),
                ('source_ts', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['node_id', 'created_at'], name='api_electri_node_id_d3fcf5_idx')],
            },
        ),
        migrations.CreateModel(
            name='FireReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=64)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('gas_level', models.FloatField()),
                ('rssi', models.IntegerField(blank=True, null=True)),
                ('source_ts', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['node_id', 'created_at'], name='api_firerea_node_id_bfaa75_idx')],
            },
        ),
    ]
